[project]
name = "backend"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "alembic>=1.20.0",
    "asyncpg>=0.31.0",
    "email-validator>=2.3.0",
    "fastapi[standard]>=0.142.2",
    "psycopg2>=2.9.13",
    "pwdlib[argon2]>=0.3.1",
    "pydantic>=2.13.5",
    "pyjwt>=2.15.1",
    "sqlalchemy[asyncio]>=2.1.2",
]
