"""Add unique constraint to user_id and event_id, add check constraint to stars count in review

Revision ID: a2a47b3f5b71
Revises: 5f68bb97e55c
Create Date: 2026-10-08 19:15:19.644197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2a47b3f5b71'
down_revision: Union[str, Sequence[str], None] = '5f68bb97e55c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_review_user_event', 'review', ['user_id', 'event_id'])
    op.create_check_constraint("ck_review_stars_range", "review", "stars_count BETWEEN 1 AND 5")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_review_user_event', 'review', type_='unique')
    op.drop_constraint("ck_review_stars_range", "review", type="check")
    # ### end Alembic commands ###
