"""Add reminder_sent column to event table

Revision ID: e4a332316752
Revises: c6b08132217b
Create Date: 2026-10-08 21:14:17.396327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4a332316752'
down_revision: Union[str, Sequence[str], None] = 'c6b08132217b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('reminder_sent', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'reminder_sent')
    # ### end Alembic commands ###
